backend:
  name: git-gateway
  branch: netifly-cms # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "stages" # Used in routes, e.g., /admin/collections/blog
    label: "stages" # Used in the UI
    folder: "content/stages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "id", name: "id", widget: "string"}
      - {label: "title", name: "title", widget: "string"}
      - {label: "stream", name: "stream", widget: "array", fields: [
          {label: "id", name: "id", widget: "string"},
        ]}